import { db } from './database.js';
import { sql } from 'kysely';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Run all pending migrations
 */
export async function runMigrations(): Promise<void> {
  await runPostgresMigrations();
}

async function runPostgresMigrations(): Promise<void> {
  // Create migrations table if it doesn't exist
  await sql`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      version INTEGER PRIMARY KEY,
      applied_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      description TEXT
    )
  `.execute(db);

  // Get current version
  const currentVersion = await db
    .selectFrom('schema_migrations')
    .select(db.fn.max('version').as('version'))
    .executeTakeFirst();

  const version = (currentVersion?.version as number) || 0;
  console.log(`Current database version: ${version}`);

  if (version < 1) {
    console.log('Running migration 001 (Postgres): Initial schema...');

    // Core tables
    await sql`
      CREATE TABLE IF NOT EXISTS seasons (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        start_date DATE,
        end_date DATE,
        is_active BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        display_name TEXT NOT NULL,
        slug TEXT UNIQUE NOT NULL,
        metadata TEXT,
        season_id INTEGER REFERENCES seasons(id),
        parent_team_id INTEGER REFERENCES teams(id),
        is_active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS team_aliases (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
        alias TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(team_id, alias)
      )
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        name TEXT NOT NULL,
        role TEXT NOT NULL CHECK (role IN ('admin', 'coach', 'viewer')),
        email_verified BOOLEAN DEFAULT FALSE,
        email_verification_token TEXT,
        email_verification_sent_at TIMESTAMPTZ,
        password_reset_token TEXT,
        password_reset_expires TIMESTAMPTZ,
        preferences TEXT,
        is_active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        last_login_at TIMESTAMPTZ
      )
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS user_teams (
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
        assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        assigned_by INTEGER REFERENCES users(id),
        PRIMARY KEY (user_id, team_id)
      )
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS sessions (
        id TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        expires_at TIMESTAMPTZ NOT NULL,
        last_activity_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS matches (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        team_id INTEGER REFERENCES teams(id),
        opponent_name TEXT NOT NULL,
        match_date DATE NOT NULL,
        competition_type TEXT,
        result TEXT,
        stats_json TEXT,
        stats_source TEXT,
        stats_computed_at TIMESTAMPTZ,
        stats_manual_fields TEXT,
        notes TEXT,
        venue TEXT,
        referee TEXT,
        created_by INTEGER REFERENCES users(id),
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        last_modified_by INTEGER REFERENCES users(id)
      )
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS game_events (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
        event_type TEXT NOT NULL,
        event_category TEXT,
        timestamp DOUBLE PRECISION,
        period INTEGER,
        minute INTEGER,
        second INTEGER,
        field_position TEXT,
        x_coordinate DOUBLE PRECISION,
        y_coordinate DOUBLE PRECISION,
        event_data TEXT,
        is_joga_team BOOLEAN DEFAULT TRUE,
        player_name TEXT,
        notes TEXT,
        tags TEXT,
        is_processed BOOLEAN DEFAULT FALSE,
        processed_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS images (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        file_path TEXT NOT NULL,
        file_name TEXT NOT NULL,
        file_size INTEGER,
        mime_type TEXT,
        width INTEGER,
        height INTEGER,
        match_id INTEGER REFERENCES matches(id) ON DELETE CASCADE,
        team_id INTEGER REFERENCES teams(id),
        description TEXT,
        uploaded_by INTEGER REFERENCES users(id),
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);

    // Indexes
    await sql`CREATE INDEX IF NOT EXISTS idx_teams_season ON teams(season_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_teams_active ON teams(is_active)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_team_aliases_alias ON team_aliases(alias)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_user_teams_user ON user_teams(user_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_user_teams_team ON user_teams(team_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_matches_team_date ON matches(team_id, match_date)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_matches_date ON matches(match_date)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_events_match ON game_events(match_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_events_type ON game_events(event_type)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_events_category ON game_events(event_category)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_events_match_type ON game_events(match_id, event_type)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_events_processed ON game_events(is_processed)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_events_timestamp ON game_events(match_id, timestamp)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_images_match ON images(match_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_images_team ON images(team_id)`.execute(db);

    await db
      .insertInto('schema_migrations')
      .values({
        version: 1,
        description: 'Initial schema - users, teams, matches, sessions',
        applied_at: new Date().toISOString(),
      })
      .execute();

    console.log('✓ Migration 001 (Postgres) completed successfully');
  }

  if (version < 2) {
    console.log('Running migration 002 (Postgres): Add email_verification_expires column...');
    await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verification_expires TIMESTAMPTZ`.execute(db);
    await db
      .insertInto('schema_migrations')
      .values({
        version: 2,
        description: 'Add email_verification_expires column for token expiry',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 002 (Postgres) completed successfully');
  }

  if (version < 3) {
    console.log('Running migration 003 (Postgres): Add structured team fields...');
    await sql`ALTER TABLE teams ADD COLUMN IF NOT EXISTS gender TEXT`.execute(db);
    await sql`ALTER TABLE teams ADD COLUMN IF NOT EXISTS level TEXT`.execute(db);
    await sql`ALTER TABLE teams ADD COLUMN IF NOT EXISTS variant TEXT DEFAULT 'volt'`.execute(db);
    await sql`ALTER TABLE teams ADD COLUMN IF NOT EXISTS birth_year_start INTEGER`.execute(db);
    await sql`ALTER TABLE teams ADD COLUMN IF NOT EXISTS birth_year_end INTEGER`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_seasons_name ON seasons(name)`.execute(db);
    await sql`UPDATE teams SET variant = 'volt' WHERE variant IS NULL OR variant = ''`.execute(db);
    await db
      .insertInto('schema_migrations')
      .values({
        version: 3,
        description: 'Add structured team fields (gender, level, variant, birth year range) and season name index',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 003 (Postgres) completed successfully');
  }

  if (version < 4) {
    console.log('Running migration 004 (Postgres): Add age_group field to teams...');
    await sql`ALTER TABLE teams ADD COLUMN IF NOT EXISTS age_group TEXT`.execute(db);
    await db
      .insertInto('schema_migrations')
      .values({
        version: 4,
        description: 'Add age_group field for flexible age group display (month range or single year)',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 004 (Postgres) completed successfully');
  }

  if (version < 5) {
    console.log('Running migration 005 (Postgres): Add metric_definitions table...');
    await sql`
      CREATE TABLE IF NOT EXISTS metric_definitions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        metric_name TEXT NOT NULL UNIQUE,
        category TEXT,
        description TEXT,
        units TEXT,
        calculation TEXT,
        notes TEXT,
        example TEXT,
        data_type TEXT,
        availability TEXT,
        source TEXT DEFAULT 'google_sheets',
        last_synced_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_metric_definitions_category ON metric_definitions(category)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_metric_definitions_name ON metric_definitions(metric_name)`.execute(db);
    await db
      .insertInto('schema_migrations')
      .values({
        version: 5,
        description: 'Add metric_definitions table for glossary feature',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 005 (Postgres) completed successfully');
  }

  if (version < 6) {
    console.log('Running migration 006 (Postgres): Add custom_charts table...');
    await sql`
      CREATE TABLE IF NOT EXISTS custom_charts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        description TEXT,
        chart_type TEXT NOT NULL CHECK (chart_type IN ('line', 'bar', 'area', 'scatter')),
        config_json TEXT NOT NULL,
        is_public BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(user_id, name)
      )
    `.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_custom_charts_user_id ON custom_charts(user_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_custom_charts_chart_type ON custom_charts(chart_type)`.execute(db);
    await db
      .insertInto('schema_migrations')
      .values({
        version: 6,
        description: 'Add custom_charts table for Phase 1 Custom Charts feature',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 006 (Postgres) completed successfully');
  }

  if (version < 7) {
    console.log('Running migration 007 (Postgres): Add is_home field to matches table...');
    await sql`
      ALTER TABLE matches
      ADD COLUMN IF NOT EXISTS is_home BOOLEAN
    `.execute(db);
    await db
      .insertInto('schema_migrations')
      .values({
        version: 7,
        description: 'Add is_home field to matches table for home/away tracking',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 007 (Postgres) completed successfully');
  }

  if (version < 8) {
    console.log('Running migration 008 (Postgres): Add match_id_external field to matches table...');
    await sql`
      ALTER TABLE matches
      ADD COLUMN IF NOT EXISTS match_id_external TEXT
    `.execute(db);
    await sql`
      CREATE INDEX IF NOT EXISTS idx_matches_match_id_external ON matches(match_id_external)
    `.execute(db);
    await db
      .insertInto('schema_migrations')
      .values({
        version: 8,
        description: 'Add match_id_external field to matches table for external Match IDs (e.g., Google Sheets)',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 008 (Postgres) completed successfully');
  }

  if (version < 9) {
    console.log('Running migration 009 (Postgres): Add insights table for Phase 1 Insights Engine...');
    await sql`
      CREATE TABLE IF NOT EXISTS insights (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
        match_id INTEGER REFERENCES matches(id) ON DELETE SET NULL,
        season_id INTEGER REFERENCES seasons(id),
        insight_type TEXT NOT NULL CHECK (insight_type IN ('anomaly', 'trend', 'half_split', 'correlation', 'benchmark')),
        category TEXT NOT NULL CHECK (category IN ('shooting', 'possession', 'passing', 'defending', 'general')),
        severity REAL NOT NULL DEFAULT 0 CHECK (severity >= 0 AND severity <= 1),
        title TEXT NOT NULL,
        detail_json TEXT NOT NULL,
        narrative TEXT,
        is_read BOOLEAN DEFAULT FALSE,
        is_dismissed BOOLEAN DEFAULT FALSE,
        expires_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_insights_team_id ON insights(team_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_insights_match_id ON insights(match_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_insights_severity ON insights(severity DESC)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_insights_is_read ON insights(is_read)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_insights_team_season ON insights(team_id, season_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_insights_type_category ON insights(insight_type, category)`.execute(db);
    await db
      .insertInto('schema_migrations')
      .values({
        version: 9,
        description: 'Add insights table for Phase 1 Insights Engine - automatic statistical detection',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 009 (Postgres) completed successfully');
  }

  if (version < 10) {
    console.log('Running migration 010 (Postgres): Add training log tables for Phase 2 Training Log...');
    
    // Training focus tags table
    await sql`
      CREATE TABLE IF NOT EXISTS training_focus_tags (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        category TEXT NOT NULL,
        display_name TEXT NOT NULL,
        sort_order INTEGER DEFAULT 0,
        is_active BOOLEAN DEFAULT TRUE
      )
    `.execute(db);
    
    // Training logs table
    await sql`
      CREATE TABLE IF NOT EXISTS training_logs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        session_date DATE NOT NULL,
        session_type TEXT DEFAULT 'training' CHECK (session_type IN ('training', 'film', 'tactical', 'fitness', 'other')),
        focus_tags TEXT NOT NULL,
        notes TEXT,
        insight_id INTEGER REFERENCES insights(id) ON DELETE SET NULL,
        recommendation_id INTEGER,
        duration_minutes INTEGER,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);
    
    // Indexes
    await sql`CREATE INDEX IF NOT EXISTS idx_training_focus_tags_category ON training_focus_tags(category)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_training_focus_tags_active ON training_focus_tags(is_active)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_training_logs_team_id ON training_logs(team_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_training_logs_user_id ON training_logs(user_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_training_logs_session_date ON training_logs(session_date)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_training_logs_insight_id ON training_logs(insight_id)`.execute(db);
    
    // Seed training focus tags
    const focusTags = [
      // POSSESSION
      { name: 'possession-general', category: 'possession', display_name: 'Possession', sort_order: 1 },
      { name: 'possession-under-pressure', category: 'possession', display_name: 'Possession Under Pressure', sort_order: 2 },
      { name: 'build-up-play', category: 'possession', display_name: 'Build-Up Play', sort_order: 3 },
      { name: 'playing-out-from-back', category: 'possession', display_name: 'Playing Out From Back', sort_order: 4 },
      { name: 'switching-play', category: 'possession', display_name: 'Switching Play', sort_order: 5 },
      { name: 'pass-strings', category: 'possession', display_name: 'Pass Strings / Combinations', sort_order: 6 },
      // ATTACKING
      { name: 'finishing', category: 'attacking', display_name: 'Finishing / Shooting', sort_order: 1 },
      { name: 'creating-chances', category: 'attacking', display_name: 'Creating Chances', sort_order: 2 },
      { name: 'movement-off-ball', category: 'attacking', display_name: 'Movement Off the Ball', sort_order: 3 },
      { name: 'crossing', category: 'attacking', display_name: 'Crossing', sort_order: 4 },
      { name: 'set-piece-attacking', category: 'attacking', display_name: 'Set Pieces — Attacking', sort_order: 5 },
      // DEFENDING
      { name: 'pressing', category: 'defending', display_name: 'Pressing / High Press', sort_order: 1 },
      { name: 'defensive-shape', category: 'defending', display_name: 'Defensive Shape', sort_order: 2 },
      { name: '1v1-defending', category: 'defending', display_name: '1v1 Defending', sort_order: 3 },
      { name: 'recovery-runs', category: 'defending', display_name: 'Recovery Runs', sort_order: 4 },
      { name: 'set-piece-defending', category: 'defending', display_name: 'Set Pieces — Defending', sort_order: 5 },
      // TRANSITION
      { name: 'counter-attack', category: 'transition', display_name: 'Counter-Attacking', sort_order: 1 },
      { name: 'counter-press', category: 'transition', display_name: 'Counter-Press / Transition Defense', sort_order: 2 },
      { name: 'transition-speed', category: 'transition', display_name: 'Transition Speed', sort_order: 3 },
      // TECHNICAL
      { name: 'first-touch', category: 'technical', display_name: 'First Touch', sort_order: 1 },
      { name: 'passing-accuracy', category: 'technical', display_name: 'Passing Accuracy', sort_order: 2 },
      { name: 'dribbling', category: 'technical', display_name: 'Dribbling / Ball Carrying', sort_order: 3 },
      { name: 'heading', category: 'technical', display_name: 'Heading', sort_order: 4 },
      // FITNESS
      { name: 'endurance', category: 'fitness', display_name: 'Endurance / 2nd Half Fitness', sort_order: 1 },
      { name: 'speed', category: 'fitness', display_name: 'Speed & Agility', sort_order: 2 },
      { name: 'game-fitness', category: 'fitness', display_name: 'Game-Realistic Fitness', sort_order: 3 },
    ];

    for (const tag of focusTags) {
      await db
        .insertInto('training_focus_tags')
        .values({
          name: tag.name,
          category: tag.category,
          display_name: tag.display_name,
          sort_order: tag.sort_order,
          is_active: true,
        })
        .onConflict((oc) => oc
          .column('name')
          .doUpdateSet({
            category: tag.category,
            display_name: tag.display_name,
            sort_order: tag.sort_order,
            is_active: true,
          })
        )
        .execute();
    }
    
    await db
      .insertInto('schema_migrations')
      .values({
        version: 10,
        description: 'Add training_focus_tags and training_logs tables for Phase 2 Training Log feature',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 010 (Postgres) completed successfully');
    console.log(`  ✓ Seeded ${focusTags.length} training focus tags`);
  }

  if (version < 11) {
    console.log('Running migration 011 (Postgres): Add AI context cache table for Phase 3...');

    // AI Context Cache table
    await sql`
      CREATE TABLE IF NOT EXISTS ai_context_cache (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
        cache_type TEXT NOT NULL DEFAULT 'combined' CHECK (cache_type IN ('combined', 'framework_only', 'data_only')),
        cache_id TEXT NOT NULL, -- Gemini's cachedContent name (e.g., "cachedContents/abc123")
        data_hash TEXT NOT NULL, -- Hash of match data to detect changes
        expires_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);

    await sql`CREATE INDEX IF NOT EXISTS idx_ai_cache_team_id ON ai_context_cache(team_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_ai_cache_type ON ai_context_cache(team_id, cache_type)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_ai_cache_expires_at ON ai_context_cache(expires_at)`.execute(db);

    await db
      .insertInto('schema_migrations')
      .values({
        version: 11,
        description: 'Add ai_context_cache table for Phase 3 Gemini Context Cache',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 011 (Postgres) completed successfully');
  }

  if (version < 12) {
    console.log('Running migration 012 (Postgres): Add recommendations table for Phase 3...');

    // Recommendations table
    await sql`
      CREATE TABLE IF NOT EXISTS recommendations (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
        insight_id INTEGER REFERENCES insights(id) ON DELETE SET NULL,
        recommendation_type TEXT NOT NULL CHECK (recommendation_type IN ('tactical', 'training', 'general')),
        category TEXT NOT NULL, -- 'shooting', 'possession', 'passing', 'defending', 'general'
        priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        action_items TEXT, -- JSON array of specific actions
        training_plan_json TEXT, -- JSON: structured training plan (optional)
        framework_alignment TEXT, -- Which US Soccer framework/license level this aligns with
        club_philosophy_alignment TEXT, -- How this aligns with club philosophy
        is_applied BOOLEAN DEFAULT FALSE,
        applied_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `.execute(db);

    await sql`CREATE INDEX IF NOT EXISTS idx_recommendations_team_id ON recommendations(team_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_recommendations_insight_id ON recommendations(insight_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_recommendations_type_category ON recommendations(recommendation_type, category)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_recommendations_priority ON recommendations(priority)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_recommendations_status ON recommendations(is_applied)`.execute(db);

    await db
      .insertInto('schema_migrations')
      .values({
        version: 12,
        description: 'Add recommendations table for Phase 3 AI-powered recommendations',
        applied_at: new Date().toISOString(),
      })
      .execute();
    console.log('✓ Migration 012 (Postgres) completed successfully');
  }

  console.log('All migrations completed!');
}
